---
http_interactions:
- request:
    method: get
    uri: http://rate-exchange.appspot.com/currency?from=EUR&q=123.45&to=USD
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Vary:
      - Accept-Encoding
      Date:
      - Tue, 06 Aug 2013 17:58:56 GMT
      Server:
      - Google Frontend
      Transfer-Encoding:
      - chunked
    body:
      encoding: UTF-8
      string: '{"to": "USD", "rate": 1.3265, "from": "EUR", "v": 163.75642500000001}'
    http_version: 
  recorded_at: Tue, 06 Aug 2013 17:58:56 GMT
recorded_with: VCR 2.5.0
