---
http_interactions:
- request:
    method: get
    uri: http://rate-exchange.appspot.com/currency?from=EUR&q=123.45&to=USD
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - Ruby
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - no-cache
      Content-Type:
      - application/json
      Vary:
      - Accept-Encoding
      Date:
      - Sun, 28 Jul 2013 22:36:28 GMT
      Server:
      - Google Frontend
      Transfer-Encoding:
      - chunked
    body:
      encoding: US-ASCII
      string: ! '{"to": "USD", "rate": 1.3275999999999999, "from": "EUR", "v": 163.89221999999998}'
    http_version: 
  recorded_at: Sun, 28 Jul 2013 22:36:28 GMT
recorded_with: VCR 2.5.0
